name: Test collection
tests:
  # SMOKE TESTING
  - name: Smoke test number 1
    global:
      timeout: 30s
      retries: 5
      retries_delay: 2s
    request:
      method: get
      uri: http://localhost:8974/products/121
      user_agent: chrome
    phases:
      - name: Phase number 1
        single_request: true